export const blockedWords = [
  "porn movie",
  "sex film",
  "xxx full movie",
  "18+ movie",
  "nude scene",
  "full nudity movie",
  "hot scene",
  "bed scene",
  "adult movie",
  "erotic movie",
  "sexy film",
  "blue film",
  "desi sex movie",
  "bollywood hot",
  "hollywood hot scene",
  "korean hot movie",
  "japanese adult video",
  "hentai movie",
  "lesbian sex scene",
  "gay sex movie",
  "uncut version",
  "unrated version",
  "nude celebrity",
  "topless scene",
  "sex tape",
  "leaked video",
  "onlyfans movie",
  "brazzers full",
  "pornhub movie",
  "xvideos film",
  "milf porn",
  "teen porn",
  "anal scene",
  "blowjob scene",
  "threesome movie",
  "orgy film",
  "gangbang movie",
  "bdsm movie",
  "incest film",
  "rape scene movie",
  "forced sex movie",
  "stepmom porn",
  "step sister sex",
  "daddy daughter",
  "mom son",
  "family sex movie",
  "taboo film",
  "cheating wife movie",
  "cuckold film",
  "swinger movie",
  "wife swap",
  "hot wife",
  "netflix sex",
  "netflix nude",
  "hot netflix series",
  "365 days sex scene",
  "fifty shades sex",
  "after sex scene",
  "elite nude",
  "dark desire hot",
  "sex/life nude",
  "bridgerton sex",
  "outlander sex scene",
  "spartacus nude",
  "game of thrones nude",
  "true blood sex",
  "euphoria nude",
  "shameless sex",
  "californication sex",
  "supersex netflix",
  "lady voyeur nude",
  "fatal seduction hot",
  "obsession netflix sex",
  "365 days full movie",
  "lady chatterley sex",
  "burning betrayal sex",
  "through my window nude",
  "ride or die sex",
  "below her mouth lesbian",
  "blue is the warmest color sex",
  "nymphomaniac full",
  "love gaspar noe",
  "9 songs sex",
  "intimacy 2001",
  "shortbus orgy",
  "ken park sex",
  "irreversible scene",
  "baise moi",
  "romance 1999",
  "in the realm of senses",
  "caligula full",
  "salò 120 days",
  "last tango in paris butter",
  "eyes wide shut orgy",
  "the dreamers sex",
  "y tu mama tambien",
  "stranger by the lake gay",
  "lie with me",
  "antichrist sex",
  "emmanuelle full",
  "black emanuelle",
  "tinto brass movie",
  "all ladies do it",
  "paprika 1991",
  "monamour",
  "cheeky tinto brass",
  "malena nude",
  "sex and lucia",
  "kama sutra movie",
  "wild orchid",
  "9½ weeks",
  "basic instinct uncut",
  "showgirls nude",
  "poison ivy 1992",
  "the lover 1992",
  "henry june",
  "original sin sex",
  "unfaithful sex",
  "killing me softly",
  "two moon junction",
  "private lessons 1981",
  "the voyeur 1994",
  "red shoe diaries",
  "shannon tweed erotic",
  "laura gemser",
  "jess franco erotic",
  "joe damato",
  "diet of sex",
  "q desire",
  "duck butter",
  "newess",
  "amar 2017",
  "milf 2018",
  "swing french",
  "superbad sex",
  "no limit netflix sex",
  "addicted 2014",
  "elisa marcela",
  "a perfect story hot",
  "indecent proposal sex",
  "american gigolo",
  "damage 1992",
  "crash 1996",
  "body heat",
  "sliver 1993",
  "fatal attraction",
  "hot hollywood",
  "hot bollywood",
  "hot korean",
  "hot japanese",
  "hot chinese movie",
  "hot thai film",
  "hot turkish series",
  "hot spanish movie",
  "hot french film",
  "hot italian erotic",
  "hot russian porn movie",
  "hot arab sex film",
  "hot indian blue film",
  "hot pakistani",
  "hot bangladeshi",
  "hot punjabi hot",
  "hot tamil sex",
  "hot telugu blue",
  "hot malayalam masala",
  "9 Songs",
  "Intimacy",
  "Nymphomaniac Vol. I & II",
  "Eyes Wide Shut",
  "Blue Is the Warmest Color",
  "Y Tu Mamá También",
  "The Dreamers",
  "Last Tango in Paris",
  "Salò, or the 120 Days of Sodom",
  "In the Realm of the Senses",
  "Lie with Me",
  "Shortbus",
  "Antichrist",
  "Love (Gaspar Noé)",
  "Stranger by the Lake",
  "Baise-moi",
  "Romance",
  "Ken Park",
  "Irreversible",
  "365 Days",
  "365 Days: This Day",
  "The Next 365 Days",
  "Fifty Shades of Grey",
  "Fifty Shades Darker",
  "Fifty Shades Freed",
  "After",
  "After We Collided",
  "Through My Window",
  "Through My Window: Across the Sea",
  "Through My Window 3: Looking at You",
  "Lady Chatterley’s Lover",
  "Burning Betrayal",
  "No Limit",
  "Ride or Die",
  "Below Her Mouth",
  "Addicted",
  "Q (Desire)",
  "Elite",
  "Dark Desire",
  "Toy Boy",
  "Valeria",
  "Sex/Life",
  "Bridgerton",
  "Outlander",
  "Spartacus",
  "The Tudors",
  "Game of Thrones",
  "True Blood",
  "Californication",
  "Shameless (US)",
  "Skins (UK)",
  "Euphoria",
  "All Ladies Do It",
  "Monamour",
  "Cheeky!",
  "Paprika",
  "Malèna",
  "Sex and Lucia",
  "Kama Sutra: A Tale of Love",
  "The Ages of Lulu",
  "The Handmaiden",
  "Portrait of a Lady on Fire",
  "Disobedience",
  "Gia",
  "Bound",
  "Lady Voyeur",
  "Obsession",
  "Fatal Seduction",
  "Supersex",
  "MILF",
  "Wild Orchid",
  "9½ Weeks",
  "Basic Instinct",
  "Showgirls",
  "Sliver",
  "Body Heat",
  "Unfaithful",
  "Original Sin",
  "The Lover",
  "Henry & June",
  "Crash (1996)",
  "Killing Me Softly",
  "Poison Ivy",
  "Emmanuelle (all classic series)",
  "Black Emanuelle series",
  "Red Shoe Diaries",
  "Private Lessons",
  "The Voyeur",
  "Frivole Games",
  "Black Angel",
  "Diet of Sex",
  "Duck Butter",
  "Newness",
  "Amar",
  "Elisa & Marcela",
  "Superbad",
  "Swing",
  "Intimate Betrayal",
  "A Perfect Story",
  "Indecent Proposal",
  "American Gigolo",
  "Damage",
  "Two Moon Junction",
  "Illicit Dreams",
  "Indecent Behavior",
  "Night Eyes",
  "Laura Gemser erotic films",
  "Jess Franco erotic films",
  "Joe D’Amato erotic films",
  "Shannon Tweed 90s erotic thrillers",
  "Desert Hearts",
  "Water Lilies",
  "Carol",
  "Imagine Me & You",
  "sex",
  "porn",
  "porno",
  "pornography",
  "xxx",
  "xvideos",
  "pornhub",
  "xnxx",
  "xhamster",
  "redtube",
  "youporn",
  "brazzers",
  "bangbros",
  "milf",
  "teen porn",
  "anal",
  "blowjob",
  "cumshot",
  "creampie",
  "gangbang",
  "orgy",
  "threesome",
  "dp",
  "double penetration",
  "fisting",
  "squirt",
  "bukkake",
  "facial",
  "deepthroat",
  "rimjob",
  "pussy",
  "dick",
  "cock",
  "tits",
  "boobs",
  "ass",
  "cunt",
  "slut",
  "whore",
  "bitch",
  "fuck",
  "fucking",
  "fucked",
  "motherfucker",
  "sexual",
  "horny",
  "nude",
  "naked",
  "nudity",
  "onlyfans",
  "camgirl",
  "camwhore",
  "escort",
  "hooker",
  "prostitute",
  "hentai",
  "rule34",
  "futa",
  "futanari",
  "loli",
  "shota",
  "lolicon",
  "shotacon",
  "incest",
  "stepmom",
  "stepsister",
  "stepbrother",
  "stepdad",
  "mom son",
  "daddy daughter",
  "family sex",
  "rape",
  "forced",
  "noncon",
  "bestiality",
  "zoophilia",
  "beastiality",
  "dog sex",
  "horse porn",
  "scat",
  "piss",
  "watersports",
  "golden shower",
  "bdsm",
  "bondage",
  "dom",
  "sub",
  "slave",
  "master",
  "dominatrix",
  "pegging",
  "strapon",
  "cuckold",
  "hotwife",
  "swinger",
  "wife sharing",
  "cheating wife",
  "bull",
  "breeding",
  "bareback",
  "raw sex",
  "sex tape",
  "leaked",
  "nudes",
  "leaked nudes",
  "celeb nudes",
  "celebrity porn",
  "deepfake porn",
  "fake porn",
  "18+",
  "adult movie",
  "blue film",
  "hot scene",
  "bed scene",
  "sex scene",
  "uncut",
  "unrated",
  "full frontal",
  "topless",
  "masturbation",
  "wank",
  "jerk off",
  "handjob",
  "footjob",
  "titjob",
  "paizuri",
  "fingering",
  "lesbian",
  "gay porn",
  "shemale",
  "tranny",
  "ladyboy",
  "trans porn",
  "ebony porn",
  "asian porn",
  "latina porn",
  "arab porn",
  "indian porn",
  "desi sex",
  "pakistani mujra",
  "bangladeshi",
  "punjabi sex",
  "tamil sex",
  "telugu blue",
  "malayalam hot",
  "bollywood hot",
  "korean hot",
  "japanese av",
  "jav uncensored",
  "chinese porn",
  "thai porn",
  "turkish sex",
  "russian porn",
  "bhabhi",
  "devar bhabhi",
  "aunty sex",
  "chachi",
  "mami",
  "mature",
  "granny porn",
  "gilf",
  "bbw",
  "fat ass",
  "big ass",
  "phat ass",
  "pawg",
  "twerk",
  "striptease",
  "dildo",
  "vibrator",
  "sex toy",
  "buttplug",
  "tentacle",
  "monster sex",
  "furry",
  "yiff",
  "gore porn",
  "snuff",
  "cp",
  "child porn",
  "underage",
  "jailbait",
  "teen",
  "barely legal",
  "virgin",
  "defloration",
  "hymen",
  "Ilsa: She Wolf of the SS",
  "She Wolf of the SS",
  "tl",
  "Tl",
  "shit",
  "s*x",
  "horror",
  "loli",
"lolicon",
"lolicons",
"lolita",
"loli hentai",
"shota",
"shotacon",
"shotacons",
"shota hentai",
"toddlercon",
"infantcon",
"childcon",
"cub",
"cubporn",
"kodomo",
"kodomo no jikan",
"ero loli",
"ero shota",
"petite hentai",
"flat chest",
"flatchest",
"small breasts hentai",
"underage hentai",
"jailbait hentai",
"barely legal hentai",
"virgin hentai",
"defloration hentai",
"hymen break",
"first time hentai",
"schoolgirl hentai",
"elementary school hentai",
"primary school hentai",
"kindergarten hentai",
"preschool hentai",
"toddler hentai",
"babycon",
"infantilism hentai",
"diaper hentai",
"age regression hentai",
"ahegao loli",
"loli rape",
"shota rape",
"loli gangbang",
"shota gangbang",
"loli incest",
"shota incest",
"loli tentacle",
"shota tentacle",
"loli monster",
"shota monster",
"loli bestiality",
"shota bestiality",
"loli dog",
"shota dog",
"loli horse",
"shota horse",
"loli impregnation",
"shota impregnation",
"loli pregnancy",
"shota pregnancy",
"loli mind break",
"shota mind break",
"loli ahegao",
"shota ahegao",
"ero lolicon",
"ero shotacon",
"mesugaki",
"brat loli",
"loli slave",
"shota slave",
"loli bondage",
"shota bondage",
"loli bdsm",
"shota bdsm",
"loli fisting",
"shota fisting",
"loli scat",
"shota scat",
"loli piss",
"shota piss",
"loli guro",
"shota guro",
"loli snuff",
"shota snuff",
"loli gore",
"shota gore",
"loli vore",
"shota vore",
"loli ryona",
"shota ryona",
"loli prostitution",
"shota prostitution",
"loli prostitution hentai",
"shota prostitution hentai",
"kodomo hentai",
"child hentai",
"underage sex hentai",
"cp hentai",
"child porn hentai",
"loli cp",
"shota cp",
"ero-anime loli",
"ero-manga loli",
"doujin loli",
"doujin shota",
"Euphoria hentai loli scenes",
"Boku no Pico",
"Pico to Chico",
"Pico x CoCo x Chico",
"Shoujo Ramune",
"Kodomono Jikan",
"Mitsudomoe loli",
"Hanamaru Kindergarten hentai",
"Non Non Biyori loli doujin",
"Papa no Iukoto wo Kikinasai loli",
"Eromanga Sensei loli",
"Sister Princess loli",
"Lucky Star loli doujin",
"K-On loli doujin",
"Ro-Kyu-Bu loli",
"Yuru Yuri loli doujin",
"Hidamari Sketch loli",
"A-Channel loli",
"Wataten loli",
"Tenshi no 3P loli",
"Loli House",
"Loli Rock",
"Imouto Paradise loli",
"Niece to Kanojo",
"Onii-chan wa Oshimai loli",
"Onani Master Kurosawa loli",
"Nozoki Ana loli",
"Yotsunoha loli",
"Imouto sae Ireba Ii loli",
"Hoshizora no Memoria loli",
"Koi to Senkyo to Chocolate loli",
"Da Capo loli",
"Clannad loli doujin",
"Kanon loli",
"Air loli doujin",
"Little Busters loli",
"Rewrite loli",
"Angel Beats loli doujin",
"Charlotte loli",
"Kampfer loli",
"Infinite Stratos loli",
"Date A Live loli",
"High School DxD loli",
"To Love Ru loli",
"Nisekoi loli",
"Oreimo loli",
"Eromanga loli",
"Saekano loli",
"Monogatari loli",
"Bakemonogatari loli",
"Nisemonogatari loli",
"Mayoi Snail loli",
"Shinobu loli",
"Hachikuji",
"Hachikuji Mayoi",
"Araragi loli",
"loli vampire",
"vampire loli",
"250 years old loli",
"1000 years old loli",
"demon loli",
"dragon loli",
"fairy loli",
"elf loli",
"catgirl loli",
"neko loli",
"fox loli",
"kitsune loli",
"succubus loli",
"slime loli",
"goblin slayer loli doujin",
"shield hero loli",
"re:zero loli",
"konosuba loli",
"overlord loli",
"slime tensei loli",
"mushoku tensei loli",
"Boku no Pico",
"Pico to Chico",
"Pico x CoCo x Chico",
"Shoujo Ramune",
"Euphoria hentai",
"Toshi Densetsu Series",
"Kanojo x Kanojo x Kanojo",
"Imouto Paradise",
"Imouto Paradise 2",
"Onii-chan wa Oshimai",
"Ero Manga Sensei hentai",
"Oreimo hentai",
"Eromanga Sensei",
"Nekopara hentai",
"Nekopara Vol 1-6",
"Monster Musume hentai",
"High School DxD hentai doujin",
"To Love Ru Darkness hentai",
"Nisekoi hentai",
"Saekano hentai",
"Monogatari hentai",
"Bakemonogatari hentai",
"Oshimonogatari",
"Mayoi Snail hentai",
"Shinobu hentai",
"Hachikuji Mayoi hentai",
"Araragi loli",
"Kiss x Sis",
"Yosuga no Sora",
"Aki Sora",
"Oni Chichi",
"Koi to Senkyo to Chocolate hentai",
"Da Capo hentai loli",
"Clannad loli doujin",
"Little Busters loli",
"Rewrite loli",
"Angel Beats loli hentai",
"Kanon loli",
"Air loli",
"School Days hentai",
"Bible Black",
"Discipline hentai",
"Night Shift Nurses",
"Stringendo",
"Accelerando",
"Haramase Simulator",
"Netorare hentai",
"Netorase",
"NTR hentai",
"Tsundero",
"Mesuiki",
"Josou Semen",
"Futanari hentai",
"Futa on male",
"Futa on female",
"Mama x Hama",
"Tsumamigui",
"Milk Junkie",
"Starless hentai",
"Kuroinu hentai",
"Taimanin Asagi",
"Taimanin Yukikaze",
"Kangoku Senkan",
"Makai Kishi Ingrid",
"Sei Shoujo hentai",
"Valkyrie Choukyou Semen Tank",
"Kyonyuu Fantasy",
"Elf no Kuni no Kyuutei Madoushi",
"Orc no Niku Banquet",
"Goblin no Su hentai",
"Goblin Slayer hentai doujin",
"Isekai hentai",
"Mushoku Tensei hentai",
"Re:Zero hentai loli",
"Konosuba hentai",
"Overlord hentai",
"Slime Tensei hentai",
"Shield Hero hentai loli",
"Date A Live hentai",
"Infinite Stratos hentai",
"Zero no Tsukaima hentai",
"Mahouka hentai",
"Fate hentai loli",
"Fate Illya hentai",
"Illyasviel hentai",
"Illya hentai",
"Illya Prisma",
"Shoujo Kakumei Utena hentai",
"Cardcaptor Sakura hentai doujin",
"Ro-Kyu-Bu hentai",
"Mitsudomoe hentai",
"Hanamaru Youchien hentai",
"Papa no Iukoto wo Kikinasai hentai",
"Wataten hentai",
"Tenshi no 3P hentai",
"Non Non Biyori hentai doujin",
"Yuru Yuri hentai",
"Hidamari Sketch hentai",
"K-On loli hentai",
"Lucky Star hentai",
"Kodomo no Jikan",
"Usagi Drop hentai (banned)",
"PapaKiki hentai",
"Loli House Rock",
"Loli Rock",
"Hoshizora no Memoria loli",
"Yotsunoha loli",
"Imouto sae Ireba Ii hentai",
"Nozoki Ana hentai",
"Saimin Seishidou",
"Saimin hentai",
"Hypnosis hentai",
"Mind control hentai",
"Ahegao hentai",
"Ahegao hoodie",
"Doujin Ahegao",
"Orcsoft hentai",
"Bishop hentai",
"Lilith hentai",
"Miel hentai",
"Norn hentai",
"Swaneye hentai",
"Queen Bee hentai",
"PoRO hentai",
"Bunnywalker",
"T-Rex hentai",
"Showten hentai",
"Mary Jane hentai",
"Pink Pineapple hentai",
"Milky hentai",
"MS Pictures hentai",
"p  o  r  n",
"p o r n",
"por n",
"p0rn",
"p0rno",
"p0rrh",
"porrn",
"pornoo",
"p*rn",
"p*o*r*n",
"po rn",
"p. o. r. n",
"porrrn",
"prn",
"p*rno",
"p ron",
"poorn",
"pornhub",
"pornhubb",
"p0rnhub",
"x v i d e o s",
"x videos",
"x video",
"xvide os",
"xvid eos",
"xv1deos",
"xham ster",
"xhamsterr",
"xhamstr",
"red tube",
"redtub",
"youporn",
"you p o r n",
"brazz ers",
"bangbr os",
"mil ff",
"milf f",
"tee n porn",
"teenp orn",
"an al",
"ana l",
"blowj ob",
"bl0wjob",
"cumsh0t",
"creamp ie",
"creamp1e",
"gangb ang",
"thr33some",
"thr33s0me",
"thr33 some",
"thr eesome",
"f u c k",
"f*ck",
"f**k",
"f u c k i n g",
"fck",
"f c k",
"f.u.c.k",
"f--k",
"f^k",
"fu ck",
"fuuuck",
"fucck",
"sh1t",
"sh!t",
"sh it",
"sh1tt",
"a s s",
"a s s h o l e",
"as shole",
"assh0le",
"p u s s y",
"puss y",
"p*ssy",
"pu ssy",
"puzzy",
"pucci",
"c o c k",
"c0ck",
"c o k",
"cok",
"c*ck",
"d i c k",
"d1ck",
"d ick",
"t i t s",
"t i t t i e s",
"titt ies",
"t1tties",
"bo obs",
"b00bs",
"b o o b s",
"boobz",
"c u n t",
"c*nt",
"c u m",
"c u m s h o t",
"j i z z",
"j1zz",
"h o r n y",
"h0rny",
"h0rni",
"n u d e",
"nud3",
"n a k e d",
"nak3d",
"n@k3d",
"onlyf ans",
"onlyf4ns",
"0nlyfans",
"camg irl",
"camwh0re",
"h e n t a i",
"h3ntai",
"hent@i",
"h3nta1",
"r u l e 3 4",
"rule34",
"r34",
"l o l i",
"l0li",
"lol1",
"l o l i c o n",
"lolicon",
"lolic0n",
"l0licon",
"s h o t a",
"sh0ta",
"shotac0n",
"sh0tacon",
"t o d d l e r c o n",
"toddlerc0n",
"infantc0n",
"c h i l d c o n",
"cp hentai",
"c p hentai",
"childp0rn",
"under age",
"underag3",
"jailb ait",
"jailb4it",
"barelylegal",
"barely legal",
"barely 18",
"v i r g i n hentai",
"virgin hentai",
"defloration",
"defl0ration",
"h y m e n",
"hymen break",
"b o k u n o p i c o",
"boku no pico",
"b0ku no pico",
"shoujo ramune",
"sh0ujo ramune",
"euphoria hentai",
"euph0ria hentai",
"k o d o m o n o j i k a n",
"kodomo no jikan",
"k0domo no jikan",
"i m o u t o p a r a d i s e",
"imouto paradise",
"im0uto paradise",
"n e t o r a r e",
"net0rare",
"n t r",
"NTR hentai",
"f u t a n a r i",
"futanari",
"futa hentai",
"f u t a",
"a h e g a o",
"ahega0",
"ahe gao",
"m i n d b r e a k",
"mindbr3ak",
"mind break hentai",
"t e n t a c l e",
"tentacl3",
"tentacle hentai",
"g o b l i n s l a y e r hentai",
"goblin rape",
"goblin hentai",
"i s e k a i hentai",
"isekai rape",
"m u s h o k u t e n s e i hentai",
"mushoku tensei r34",
"r e z e r o l o l i",
"re zero felix",
"re zero femboy",
"k o n o s u b a megumin hentai",
"megumin loli",
"o v e r l o r d albedo hentai",
"tainted hentai",
"k a n k o l l e c t i o n",
"kancolle loli",
"f a t e i l l y a hentai",
"illya hentai",
"illyasviel hentai",
"prillya hentai",
"s a i m i n s e i s h i d o u",
"saimin hentai",
"hypn0sis hentai",
"m i l k y hentai",
"pink pineapple hentai",
"queen bee hentai",
"t r e x hentai",
"showten hentai",
"b i s h o p hentai",
"l i l i t h hentai",
"m i e l hentai",
"m o n s t e r m u s u m e hentai",
"highschool dxd r34",
"to love ru darkness hentai",
"n e k o p a r a hentai",
"nek0para hentai",
"o n i i c h i c h i",
"oni chichi",
"on1chichi",
"k i s s x s i s",
"kissxsis",
"y o s u g a n o s o r a",
"yosuga no sora hentai",
"a k i s o r a",
"aki sora hentai",
"b i b l e b l a c k",
"bible black hentai",
"n i g h t s h i f t n u r s e s",
"night shift nurses",
"d i s c i p l i n e hentai",
"discipline hentai",
"s t a r l e s s hentai",
"starless hentai",
"k u r o i n u hentai",
"kuroinu hentai",
"t a i m a n i n a s a g i",
"taimanin asagi",
"t a i m a n i n y u k i k a z e",
"taimanin yukikaze"
];
